apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-master-present
  namespace: dev-ns-integrador
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/success-codes: 200,301,302
    alb.ingress.kubernetes.io/tags: Environment=dev-api-master-present,Team=${ORG},App=api-master-present

spec:
  rules:
  - host: dev-api-google-auth.master.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev-api-master-present
            port:
              number: 80
